//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.1
//     from Assets/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""プレイヤー"",
            ""id"": ""2a2bcd05-0494-4a9c-8828-45e5f5e38a7e"",
            ""actions"": [
                {
                    ""name"": ""いどう"",
                    ""type"": ""Value"",
                    ""id"": ""a250dc6e-76cc-492f-803c-3b53bbe6df95"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ジャンプ"",
                    ""type"": ""Button"",
                    ""id"": ""7f6d93e5-bd0b-4095-bcc3-a687928f91b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ダッシュ"",
                    ""type"": ""Value"",
                    ""id"": ""798623dc-6c31-47df-9cf8-f6d52086f268"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""パワーアップアクション"",
                    ""type"": ""Button"",
                    ""id"": ""65f84768-f346-4525-b429-95d650c37964"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""イテムをとりだします"",
                    ""type"": ""Button"",
                    ""id"": ""27ec6a67-2030-438e-ab5f-3e20fddb0588"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Primary"",
                    ""id"": ""b59a628e-7154-4ff9-bb0d-0260ee9ce0b8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""いどう"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f4cee09a-4bcc-43b8-b20b-0b57fbd70b7b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""いどう"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3153a706-5fa4-4142-9c27-9e164e4c034f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""いどう"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2f964f02-ce9f-4fa3-9e04-ec8475b63750"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""いどう"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""251c594b-959a-45c5-89e4-821f19984754"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""いどう"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Secondary"",
                    ""id"": ""8ed575b7-5e34-4b39-8574-390a5d196f13"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""いどう"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7cf1f77e-cf94-4309-a527-cde0402deb79"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""いどう"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0a90ca7c-bc1f-4a56-bec0-9b95fe6c1831"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""いどう"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b7303a97-a46d-4875-afc3-26389a2ff9eb"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""いどう"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7b2d6e4e-fc09-4d26-be15-8be412f13a51"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""いどう"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""054c937f-88cd-4578-81fb-194c4a921e24"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""いどう"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f59fb87-e484-45bd-881b-62a7af753825"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""いどう"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""789ffe33-e419-434e-8941-e24090cf8a74"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""ジャンプ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a077bd36-864d-41c8-b34b-863cbcc49ecf"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""ジャンプ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0556edb9-c870-47fd-bf53-4bb653bb9bd5"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""ジャンプ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e0290b6-117e-4dbd-81ef-4c83bddd3391"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""ジャンプ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ef1392a-775f-4a10-9591-28cc460c1aa1"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""パワーアップアクション"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b284224-af05-4e95-8374-101e01be02d5"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""パワーアップアクション"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e90050c4-9cc2-409f-a975-0dab0fbff190"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""パワーアップアクション"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""333b6c30-fc28-4f7b-8ef9-10531c0db276"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""パワーアップアクション"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78efe07a-1e6a-456b-b6fb-42480be84cc3"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""イテムをとりだします"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95f2f5d9-dd1c-45a8-93ca-413d282b0773"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""イテムをとりだします"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10c0c973-147b-4d97-8bdc-d2021ca6f0d7"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""イテムをとりだします"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1345dc5-3f4f-406a-a98b-21bac59f672d"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""イテムをとりだします"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c6a824a-127d-4a16-bbb0-fbf98dc33c60"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""ダッシュ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1c5bf80-bd76-4405-88a9-0949f8dc2387"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""ダッシュ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40223f13-16dd-46c0-b295-57edb60d3de6"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""ダッシュ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76651f3d-3a36-4be9-b752-b55ded85dcea"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""ダッシュ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""インターフェース"",
            ""id"": ""407e7f51-380f-4302-9bff-60ad8404c389"",
            ""actions"": [
                {
                    ""name"": ""UIのそうさ"",
                    ""type"": ""Value"",
                    ""id"": ""b072402b-cb37-44ad-ad92-a6bfd444a263"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""けってい"",
                    ""type"": ""Button"",
                    ""id"": ""758ce95c-f766-4c5d-8d4a-dd89249ab100"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""キャンセル"",
                    ""type"": ""Button"",
                    ""id"": ""c84903a3-a408-4390-bec1-f830d54ea872"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ポーズ"",
                    ""type"": ""Button"",
                    ""id"": ""f9cfbe05-8f85-454a-b6ad-67e0f242a73a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""スコアボード"",
                    ""type"": ""Button"",
                    ""id"": ""ea6fc54f-16db-43be-9e14-c6c27a387e06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""デバックじょうほう"",
                    ""type"": ""Button"",
                    ""id"": ""8cc650dc-a45e-4887-b332-7b0fdfdb1106"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""!SpectatePlayerByIndex"",
                    ""type"": ""Button"",
                    ""id"": ""39bd28f4-bd03-4374-9e6f-ba1c13f41a2c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""!Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5c7013a5-1581-4d40-9965-05d3486faf12"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""!Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""528240f0-81db-4042-b0fb-509d2b15e7ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""!ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8b11591d-f107-4fa6-8858-eadb2b8a96ea"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""!MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6b5ee6dd-9c9e-4e74-9461-fe743c15623f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""!RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""170943c8-16ac-4712-90c4-0292b6c875b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Primary"",
                    ""id"": ""b8c1a963-5646-4ede-9999-ca41cc9d8227"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIのそうさ"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a458c173-cb24-4b71-858b-ddf324964943"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""UIのそうさ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6db7a2da-9db8-4063-90c7-e851221b3695"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""UIのそうさ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""02021990-516a-4174-8315-b7de8c412e5d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""UIのそうさ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""201dd7c0-7dcf-4d64-8fd9-626d2670cc62"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""UIのそうさ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Secondary"",
                    ""id"": ""0f7fe809-c8c2-4464-bd5c-8a9608fc44de"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIのそうさ"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""77b86336-7581-4f7e-9332-2bf2b538c97f"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""UIのそうさ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b290b858-d3e5-4a45-9aba-312dad6a4bc1"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""UIのそうさ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ddeeb9b2-0bee-414b-a5c1-ef1b9c2dd7ea"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""UIのそうさ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""42d929b1-c987-4dde-82b1-44e15891c5fe"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""UIのそうさ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2ad93afa-2a17-47a0-bf4a-46ae7727fd77"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""UIのそうさ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3094aac2-8609-468a-b0ff-beadb0bea409"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""UIのそうさ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c9083dd-836f-4a65-b122-f0938558e0b7"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""けってい"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8eb51837-064d-4aa1-b909-70a4979b3cf6"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""けってい"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73d831f4-4a8b-47e5-91d4-cb871d14f10e"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""けってい"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c2e4b2e-322a-4fb2-a53f-d9297c00f294"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""けってい"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cdf8e2fe-2324-4575-ad6d-87893e5dfa7e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""キャンセル"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ce21316-8bdd-4459-9f35-b2b7a943f50d"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""キャンセル"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7d3d7b1-d1ba-4078-8498-9921e9378002"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;キーボード;ゲームパッド"",
                    ""action"": ""!Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e9b071f-e8c4-46e5-bff5-350937122503"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;キーボード;ゲームパッド"",
                    ""action"": ""!Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac552b38-af0d-4d31-b3d2-6149755264b4"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch;キーボード;ゲームパッド"",
                    ""action"": ""!Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19d24f91-66c4-423d-8e14-3d61d3e98bdf"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;キーボード;ゲームパッド"",
                    ""action"": ""!Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a9a8c81-293a-4b4e-ba81-13b8a1d44b60"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;ゲームパッド;キーボード"",
                    ""action"": ""!Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54dbd588-b0f0-4ef7-8c30-3a6e0bb40ab8"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch;キーボード;ゲームパッド"",
                    ""action"": ""!Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a6ec4b3-3d42-4c8f-bae6-5ec9aad39a99"",
                    ""path"": ""<XRController>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR;キーボード;ゲームパッド"",
                    ""action"": ""!Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b53f879-45a9-4ed9-84a1-51578ac3350e"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード;ゲームパッド"",
                    ""action"": ""!ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3295267d-54a8-4b1d-9241-f038f2eab6a3"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード;ゲームパッド"",
                    ""action"": ""!MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c3e9795-8ce4-4d9a-aeba-8cb1deed8517"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード;ゲームパッド"",
                    ""action"": ""!RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7126d1c8-2e9c-49b1-8597-f8b81502813e"",
                    ""path"": ""*/{Back}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""キャンセル"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2291fc1-597a-4324-a672-0060af7a8ea0"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""キャンセル"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84d5c5e1-d65d-4189-bb30-43ec38191741"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""ポーズ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50eccd33-7a45-4940-8d41-11baa00532bc"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""ポーズ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""577a7667-f002-4e0c-ae5d-2eea7a9cce33"",
                    ""path"": ""*/{Menu}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""ポーズ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7bbc802-9936-4a1d-a1d5-dd5dfa244516"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""ポーズ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b8a9c51-6fb0-4003-b3da-e9c59e91d92e"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""デバックじょうほう"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0267a921-9477-4fca-a466-67d3fece6585"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""デバックじょうほう"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcc0af49-9727-421a-ba9c-493d50b2caaa"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""デバックじょうほう"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce5c24b0-8663-43ab-b7cc-40433414bbf1"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""デバックじょうほう"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18c51067-d4f9-4332-a5aa-24899ebb4169"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""スコアボード"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c696f9d-0e41-4ebd-b149-ddc9b1de7e75"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""スコアボード"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab1a59d9-4d52-47ea-a631-a030a7416738"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""スコアボード"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70b52a60-bdd3-4fbb-81a2-47f9a138f871"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ゲームパッド"",
                    ""action"": ""スコアボード"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6f43dbf-b53a-4832-900b-ca266c63ae0f"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""!SpectatePlayerByIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f506dc70-8046-4aa2-a797-1b2c7df9233a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""!SpectatePlayerByIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1c10f98-e0b9-4171-833f-716740878d02"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""!SpectatePlayerByIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""451d5f9a-f5d7-4bda-a1b8-d9b9552451f9"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""!SpectatePlayerByIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8d268b1-079c-448b-880e-4f4ae2f094e2"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""!SpectatePlayerByIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d5b9750-f5e5-45e0-8058-a9478468a4fc"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""!SpectatePlayerByIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5eb00f43-115c-4c75-aca0-c7a6a95530da"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""!SpectatePlayerByIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72446320-c46f-4b4e-bb40-2b88e67ec3b1"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""!SpectatePlayerByIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fda8aab5-61bf-4cc9-9ba0-7af81bf63d9b"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""!SpectatePlayerByIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcdaac98-a2ed-4fe5-97e0-74b71cdfac3a"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""キーボード"",
                    ""action"": ""!SpectatePlayerByIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""キーボード"",
            ""bindingGroup"": ""キーボード"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""ゲームパッド"",
            ""bindingGroup"": ""ゲームパッド"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // プレイヤー
        m_プレイヤー = asset.FindActionMap("プレイヤー", throwIfNotFound: true);
        m_プレイヤー_いどう = m_プレイヤー.FindAction("いどう", throwIfNotFound: true);
        m_プレイヤー_ジャンプ = m_プレイヤー.FindAction("ジャンプ", throwIfNotFound: true);
        m_プレイヤー_ダッシュ = m_プレイヤー.FindAction("ダッシュ", throwIfNotFound: true);
        m_プレイヤー_パワーアップアクション = m_プレイヤー.FindAction("パワーアップアクション", throwIfNotFound: true);
        m_プレイヤー_イテムをとりだします = m_プレイヤー.FindAction("イテムをとりだします", throwIfNotFound: true);
        // インターフェース
        m_インターフェース = asset.FindActionMap("インターフェース", throwIfNotFound: true);
        m_インターフェース_UIのそうさ = m_インターフェース.FindAction("UIのそうさ", throwIfNotFound: true);
        m_インターフェース_けってい = m_インターフェース.FindAction("けってい", throwIfNotFound: true);
        m_インターフェース_キャンセル = m_インターフェース.FindAction("キャンセル", throwIfNotFound: true);
        m_インターフェース_ポーズ = m_インターフェース.FindAction("ポーズ", throwIfNotFound: true);
        m_インターフェース_スコアボード = m_インターフェース.FindAction("スコアボード", throwIfNotFound: true);
        m_インターフェース_デバックじょうほう = m_インターフェース.FindAction("デバックじょうほう", throwIfNotFound: true);
        m_インターフェース_SpectatePlayerByIndex = m_インターフェース.FindAction("!SpectatePlayerByIndex", throwIfNotFound: true);
        m_インターフェース_Point = m_インターフェース.FindAction("!Point", throwIfNotFound: true);
        m_インターフェース_Click = m_インターフェース.FindAction("!Click", throwIfNotFound: true);
        m_インターフェース_ScrollWheel = m_インターフェース.FindAction("!ScrollWheel", throwIfNotFound: true);
        m_インターフェース_MiddleClick = m_インターフェース.FindAction("!MiddleClick", throwIfNotFound: true);
        m_インターフェース_RightClick = m_インターフェース.FindAction("!RightClick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // プレイヤー
    private readonly InputActionMap m_プレイヤー;
    private IプレイヤーActions m_プレイヤーActionsCallbackInterface;
    private readonly InputAction m_プレイヤー_いどう;
    private readonly InputAction m_プレイヤー_ジャンプ;
    private readonly InputAction m_プレイヤー_ダッシュ;
    private readonly InputAction m_プレイヤー_パワーアップアクション;
    private readonly InputAction m_プレイヤー_イテムをとりだします;
    public struct プレイヤーActions
    {
        private @Controls m_Wrapper;
        public プレイヤーActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @いどう => m_Wrapper.m_プレイヤー_いどう;
        public InputAction @ジャンプ => m_Wrapper.m_プレイヤー_ジャンプ;
        public InputAction @ダッシュ => m_Wrapper.m_プレイヤー_ダッシュ;
        public InputAction @パワーアップアクション => m_Wrapper.m_プレイヤー_パワーアップアクション;
        public InputAction @イテムをとりだします => m_Wrapper.m_プレイヤー_イテムをとりだします;
        public InputActionMap Get() { return m_Wrapper.m_プレイヤー; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(プレイヤーActions set) { return set.Get(); }
        public void SetCallbacks(IプレイヤーActions instance)
        {
            if (m_Wrapper.m_プレイヤーActionsCallbackInterface != null)
            {
                @いどう.started -= m_Wrapper.m_プレイヤーActionsCallbackInterface.Onいどう;
                @いどう.performed -= m_Wrapper.m_プレイヤーActionsCallbackInterface.Onいどう;
                @いどう.canceled -= m_Wrapper.m_プレイヤーActionsCallbackInterface.Onいどう;
                @ジャンプ.started -= m_Wrapper.m_プレイヤーActionsCallbackInterface.Onジャンプ;
                @ジャンプ.performed -= m_Wrapper.m_プレイヤーActionsCallbackInterface.Onジャンプ;
                @ジャンプ.canceled -= m_Wrapper.m_プレイヤーActionsCallbackInterface.Onジャンプ;
                @ダッシュ.started -= m_Wrapper.m_プレイヤーActionsCallbackInterface.Onダッシュ;
                @ダッシュ.performed -= m_Wrapper.m_プレイヤーActionsCallbackInterface.Onダッシュ;
                @ダッシュ.canceled -= m_Wrapper.m_プレイヤーActionsCallbackInterface.Onダッシュ;
                @パワーアップアクション.started -= m_Wrapper.m_プレイヤーActionsCallbackInterface.Onパワーアップアクション;
                @パワーアップアクション.performed -= m_Wrapper.m_プレイヤーActionsCallbackInterface.Onパワーアップアクション;
                @パワーアップアクション.canceled -= m_Wrapper.m_プレイヤーActionsCallbackInterface.Onパワーアップアクション;
                @イテムをとりだします.started -= m_Wrapper.m_プレイヤーActionsCallbackInterface.Onイテムをとりだします;
                @イテムをとりだします.performed -= m_Wrapper.m_プレイヤーActionsCallbackInterface.Onイテムをとりだします;
                @イテムをとりだします.canceled -= m_Wrapper.m_プレイヤーActionsCallbackInterface.Onイテムをとりだします;
            }
            m_Wrapper.m_プレイヤーActionsCallbackInterface = instance;
            if (instance != null)
            {
                @いどう.started += instance.Onいどう;
                @いどう.performed += instance.Onいどう;
                @いどう.canceled += instance.Onいどう;
                @ジャンプ.started += instance.Onジャンプ;
                @ジャンプ.performed += instance.Onジャンプ;
                @ジャンプ.canceled += instance.Onジャンプ;
                @ダッシュ.started += instance.Onダッシュ;
                @ダッシュ.performed += instance.Onダッシュ;
                @ダッシュ.canceled += instance.Onダッシュ;
                @パワーアップアクション.started += instance.Onパワーアップアクション;
                @パワーアップアクション.performed += instance.Onパワーアップアクション;
                @パワーアップアクション.canceled += instance.Onパワーアップアクション;
                @イテムをとりだします.started += instance.Onイテムをとりだします;
                @イテムをとりだします.performed += instance.Onイテムをとりだします;
                @イテムをとりだします.canceled += instance.Onイテムをとりだします;
            }
        }
    }
    public プレイヤーActions @プレイヤー => new プレイヤーActions(this);

    // インターフェース
    private readonly InputActionMap m_インターフェース;
    private IインターフェースActions m_インターフェースActionsCallbackInterface;
    private readonly InputAction m_インターフェース_UIのそうさ;
    private readonly InputAction m_インターフェース_けってい;
    private readonly InputAction m_インターフェース_キャンセル;
    private readonly InputAction m_インターフェース_ポーズ;
    private readonly InputAction m_インターフェース_スコアボード;
    private readonly InputAction m_インターフェース_デバックじょうほう;
    private readonly InputAction m_インターフェース_SpectatePlayerByIndex;
    private readonly InputAction m_インターフェース_Point;
    private readonly InputAction m_インターフェース_Click;
    private readonly InputAction m_インターフェース_ScrollWheel;
    private readonly InputAction m_インターフェース_MiddleClick;
    private readonly InputAction m_インターフェース_RightClick;
    public struct インターフェースActions
    {
        private @Controls m_Wrapper;
        public インターフェースActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @UIのそうさ => m_Wrapper.m_インターフェース_UIのそうさ;
        public InputAction @けってい => m_Wrapper.m_インターフェース_けってい;
        public InputAction @キャンセル => m_Wrapper.m_インターフェース_キャンセル;
        public InputAction @ポーズ => m_Wrapper.m_インターフェース_ポーズ;
        public InputAction @スコアボード => m_Wrapper.m_インターフェース_スコアボード;
        public InputAction @デバックじょうほう => m_Wrapper.m_インターフェース_デバックじょうほう;
        public InputAction @SpectatePlayerByIndex => m_Wrapper.m_インターフェース_SpectatePlayerByIndex;
        public InputAction @Point => m_Wrapper.m_インターフェース_Point;
        public InputAction @Click => m_Wrapper.m_インターフェース_Click;
        public InputAction @ScrollWheel => m_Wrapper.m_インターフェース_ScrollWheel;
        public InputAction @MiddleClick => m_Wrapper.m_インターフェース_MiddleClick;
        public InputAction @RightClick => m_Wrapper.m_インターフェース_RightClick;
        public InputActionMap Get() { return m_Wrapper.m_インターフェース; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(インターフェースActions set) { return set.Get(); }
        public void SetCallbacks(IインターフェースActions instance)
        {
            if (m_Wrapper.m_インターフェースActionsCallbackInterface != null)
            {
                @UIのそうさ.started -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnUIのそうさ;
                @UIのそうさ.performed -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnUIのそうさ;
                @UIのそうさ.canceled -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnUIのそうさ;
                @けってい.started -= m_Wrapper.m_インターフェースActionsCallbackInterface.Onけってい;
                @けってい.performed -= m_Wrapper.m_インターフェースActionsCallbackInterface.Onけってい;
                @けってい.canceled -= m_Wrapper.m_インターフェースActionsCallbackInterface.Onけってい;
                @キャンセル.started -= m_Wrapper.m_インターフェースActionsCallbackInterface.Onキャンセル;
                @キャンセル.performed -= m_Wrapper.m_インターフェースActionsCallbackInterface.Onキャンセル;
                @キャンセル.canceled -= m_Wrapper.m_インターフェースActionsCallbackInterface.Onキャンセル;
                @ポーズ.started -= m_Wrapper.m_インターフェースActionsCallbackInterface.Onポーズ;
                @ポーズ.performed -= m_Wrapper.m_インターフェースActionsCallbackInterface.Onポーズ;
                @ポーズ.canceled -= m_Wrapper.m_インターフェースActionsCallbackInterface.Onポーズ;
                @スコアボード.started -= m_Wrapper.m_インターフェースActionsCallbackInterface.Onスコアボード;
                @スコアボード.performed -= m_Wrapper.m_インターフェースActionsCallbackInterface.Onスコアボード;
                @スコアボード.canceled -= m_Wrapper.m_インターフェースActionsCallbackInterface.Onスコアボード;
                @デバックじょうほう.started -= m_Wrapper.m_インターフェースActionsCallbackInterface.Onデバックじょうほう;
                @デバックじょうほう.performed -= m_Wrapper.m_インターフェースActionsCallbackInterface.Onデバックじょうほう;
                @デバックじょうほう.canceled -= m_Wrapper.m_インターフェースActionsCallbackInterface.Onデバックじょうほう;
                @SpectatePlayerByIndex.started -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnSpectatePlayerByIndex;
                @SpectatePlayerByIndex.performed -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnSpectatePlayerByIndex;
                @SpectatePlayerByIndex.canceled -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnSpectatePlayerByIndex;
                @Point.started -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnPoint;
                @Click.started -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnClick;
                @ScrollWheel.started -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.performed -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.canceled -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnScrollWheel;
                @MiddleClick.started -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.performed -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.canceled -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnMiddleClick;
                @RightClick.started -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_インターフェースActionsCallbackInterface.OnRightClick;
            }
            m_Wrapper.m_インターフェースActionsCallbackInterface = instance;
            if (instance != null)
            {
                @UIのそうさ.started += instance.OnUIのそうさ;
                @UIのそうさ.performed += instance.OnUIのそうさ;
                @UIのそうさ.canceled += instance.OnUIのそうさ;
                @けってい.started += instance.Onけってい;
                @けってい.performed += instance.Onけってい;
                @けってい.canceled += instance.Onけってい;
                @キャンセル.started += instance.Onキャンセル;
                @キャンセル.performed += instance.Onキャンセル;
                @キャンセル.canceled += instance.Onキャンセル;
                @ポーズ.started += instance.Onポーズ;
                @ポーズ.performed += instance.Onポーズ;
                @ポーズ.canceled += instance.Onポーズ;
                @スコアボード.started += instance.Onスコアボード;
                @スコアボード.performed += instance.Onスコアボード;
                @スコアボード.canceled += instance.Onスコアボード;
                @デバックじょうほう.started += instance.Onデバックじょうほう;
                @デバックじょうほう.performed += instance.Onデバックじょうほう;
                @デバックじょうほう.canceled += instance.Onデバックじょうほう;
                @SpectatePlayerByIndex.started += instance.OnSpectatePlayerByIndex;
                @SpectatePlayerByIndex.performed += instance.OnSpectatePlayerByIndex;
                @SpectatePlayerByIndex.canceled += instance.OnSpectatePlayerByIndex;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
                @MiddleClick.started += instance.OnMiddleClick;
                @MiddleClick.performed += instance.OnMiddleClick;
                @MiddleClick.canceled += instance.OnMiddleClick;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
            }
        }
    }
    public インターフェースActions @インターフェース => new インターフェースActions(this);
    private int m_キーボードSchemeIndex = -1;
    public InputControlScheme キーボードScheme
    {
        get
        {
            if (m_キーボードSchemeIndex == -1) m_キーボードSchemeIndex = asset.FindControlSchemeIndex("キーボード");
            return asset.controlSchemes[m_キーボードSchemeIndex];
        }
    }
    private int m_ゲームパッドSchemeIndex = -1;
    public InputControlScheme ゲームパッドScheme
    {
        get
        {
            if (m_ゲームパッドSchemeIndex == -1) m_ゲームパッドSchemeIndex = asset.FindControlSchemeIndex("ゲームパッド");
            return asset.controlSchemes[m_ゲームパッドSchemeIndex];
        }
    }
    public interface IプレイヤーActions
    {
        void Onいどう(InputAction.CallbackContext context);
        void Onジャンプ(InputAction.CallbackContext context);
        void Onダッシュ(InputAction.CallbackContext context);
        void Onパワーアップアクション(InputAction.CallbackContext context);
        void Onイテムをとりだします(InputAction.CallbackContext context);
    }
    public interface IインターフェースActions
    {
        void OnUIのそうさ(InputAction.CallbackContext context);
        void Onけってい(InputAction.CallbackContext context);
        void Onキャンセル(InputAction.CallbackContext context);
        void Onポーズ(InputAction.CallbackContext context);
        void Onスコアボード(InputAction.CallbackContext context);
        void Onデバックじょうほう(InputAction.CallbackContext context);
        void OnSpectatePlayerByIndex(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnMiddleClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
    }
}
